branch-defaults:
  default:
    environment: django-abeatameal-env
    group_suffix: null
global:
  application_name: django-abeatameal
  branch: null
  default_ec2_keyname: aws_rsa2
  default_platform: Python 2.7
  default_region: eu-west-1
  profile: eb-cli
  repository: null
  sc: null
