# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 13:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('index', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('index', models.IntegerField(default=0)),
                ('pic', models.URLField()),
                ('recipe', models.URLField()),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='PairPreferance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0)),
                ('index', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=2)),
                ('date', models.DateField(default=datetime.date(2016, 9, 21))),
                ('time', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_index', models.IntegerField(default=0)),
                ('dob', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('U', 'Undisclosed'), ('F', 'Female'), ('M', 'Male')], default='U', max_length=1)),
                ('allergies', models.CharField(default='0', max_length=128)),
                ('diet', models.CharField(default='0', max_length=128)),
                ('occupation', models.IntegerField(default=0)),
                ('nationality', models.CharField(default='0', max_length=128)),
                ('slug', models.SlugField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
