# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 12:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('items', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('slug', models.SlugField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('users', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('home', models.IntegerField(default=0)),
                ('meal', models.IntegerField(default=0)),
                ('menu', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('pref', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('cooking', models.BooleanField(default=False)),
                ('pickup', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('users', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('pref', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('index', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('index', models.IntegerField(default=0)),
                ('pic', models.URLField(blank=True)),
                ('recipe', models.URLField(blank=True)),
                ('ingrs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('cuisines', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('allergies', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('diets', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('slug', models.SlugField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PairPreferance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0)),
                ('index', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=2)),
                ('date', models.DateField(default=datetime.date(2016, 10, 24))),
                ('time', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Preferance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField(default=0)),
                ('rank', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('model', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('pairs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('ready', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.IntegerField(default=0)),
                ('pref', models.IntegerField(default=0)),
                ('dob', models.DateField(default=0)),
                ('gender', models.CharField(choices=[('U', 'Undisclosed'), ('F', 'Female'), ('M', 'Male')], default='U', max_length=1)),
                ('allergies', models.CharField(default='0', max_length=128)),
                ('diet', models.CharField(default='0', max_length=128)),
                ('hunger', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
