# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 15:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_auto_20161024_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
