# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_auto_20161024_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferance',
            name='ownertype',
            field=models.BooleanField(default=False),
        ),
    ]
