# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_auto_20160921_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='slug',
            field=models.SlugField(max_length=128),
        ),
    ]
